image: alpine:3.5

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install wurlitzer Pillow scipy sphinx sphinx_rtd_theme pytest
  - apk --no-cache add make
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - refactoring
