image: continuumio/miniconda

before_script:
  - apt-get update && apt-get install make
  - conda create -c rdkit -n rdkit-doc rdkit python=3.6.1
  - source activate rdkit-doc
  - pip install git+https://github.com/glenveegee/PDBeCIF.git  
  - pip install Pillow scipy sphinx sphinx_rtd_theme pytest
  - pip install -e .

test:
  script:
  - pytest

  only:
  - refactoring

pages:
  script:
  - cd doc
  - make html
  - mv _build/html/ ../public/
  
  artifacts:
    paths:
    - public
  only:
  - refactoring

