image: continuumio/miniconda

before_script:
  - apt-get update && apt-get install make
  - conda create -c rdkit -n rdkit-doc rdkit python=3.6.5
  - source activate rdkit-doc
  - pip install -e .
  - pip install pytest-cov sphinx sphinx_rtd_theme recommonmark

test:
  script:
  - pytest --cov=pdbeccdutils

  only:
  - master

pages:
  script:
  - cd doc
  - make html
  - mv _build/html/ ../public/
  
  artifacts:
    paths:
    - public
  only:
  - master

