image: continuumio/miniconda

pages:
  before_script:
  - ls
  - apt-get update && apt-get install make
  - conda create -c rdkit -n rdkit-doc rdkit python=3.6.1
  - source activate rdkit-doc
  - pip install git+https://github.com/glenveegee/PDBeCIF.git  
  - pip install wurlitzer Pillow scipy sphinx sphinx_rtd_theme pytest
  - pip install -e .

  script:
  - cd doc
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - refactoring
