# This workflow will install Python dependencies, run tests and generate ccdutils documentation

name: ccdutils tests

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  pytest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false    
    
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Set up environment and run pytest
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
        conda-channels: rdkit 
    - run: |
        conda install rdkit
        pip install -e .
        pip install pytest-cov
        pytest --cov=pdbeccdutils
