# This workflow will install Python dependencies, run pytests

name: ccdutils tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  pytest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up environment and run pytest
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          conda-channels: conda-forge
      - run: |
          conda install rdkit=2022.09.4
          pip install -e ".[tests]"
          pip install pre-commit
          pre-commit install && pre-commit run --all
      - run: pytest --cov=pdbeccdutils
